services:
  app:
    image: fmcdev/franklinmartin.dev:main
    container_name: fmweb
    restart: always
    networks:
      - app-network
    working_dir: /app
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
    - "/srv/proxy/certbot/www/:/var/www/:rw"
    - "/srv/proxy/certbot/conf/:/etc/letsencrypt/:rw"
    depends_on:
      - app
    networks:
      - app-network
  
networks:
  app-network:
    driver: bridge