services:
  app:
    image: fmcdev/franklinmartin.dev:main
    container_name: fmweb
    restart: always
    networks:
      - app-network
    working_dir: /app
  proxy:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "/srv/proxy/conf/:/etc/nginx/conf.d/:ro"
      - "/srv/proxy/certbot/www/:/var/www/:ro"
      - "/srv/proxy/certbot/conf/:/etc/nginx/ssl/:ro"
    depends_on:
      - app
    networks:
      - app-network
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
    - "/srv/proxy/certbot/www/:/var/www/:rw"
    - "/srv/proxy/certbot/conf/:/etc/letsencrypt/:rw"
    depends_on:
      - proxy
  
networks:
  app-network:
    driver: bridge