services:
  app:
    image: fmcdev/franklinmartin.dev:main
    container_name: fmweb
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/srv/proxy/certbot/www/:/var/www/certbot/:ro"
      - "/srv/proxy/certbot/conf/:/etc/nginx/ssl/:ro"
    working_dir: /app
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
    - "/srv/proxy/certbot/www/:/var/www/certbot/:rw"
    - "/srv/proxy/certbot/conf/:/etc/letsencrypt/:rw"